services:
  - type: web
    name: weblamnhiemvu
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    databases:
      - name: weblamnhiemvu-db
        databaseName: weblamnhiemvu_db
        user: weblamnhiemvu_user